# Generated by Django 5.2.8 on 2025-11-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detailed_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Подробное описание задачи'),
        ),
    ]
